src/Entity/CtImprimeTechUse.php
<?php

namespace App\Entity;

use App\Repository\CtImprimeTechUseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CtImprimeTechUseRepository::class)
 */
class CtImprimeTechUse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=CtBordereau::class, inversedBy="ctImprimeTechUses")
     */
    private $ct_bordereau_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtCentre::class, inversedBy="ctImprimeTechUses")
     */
    private $ct_centre_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtImprimeTech::class, inversedBy="ctImprimeTechUses")
     */
    private $ct_imprime_tech_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtUser::class, inversedBy="ctImprimeTechUses")
     */
    private $ct_user_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ct_controle_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $itu_numero;

    /**
     * @ORM\Column(type="boolean")
     */
    private $itu_used;

    /**
     * @ORM\ManyToOne(targetEntity=CtUsageImprimeTechnique::class, inversedBy="ctImprimeTechUses")
     */
    private $ct_usage_it_id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $actived_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $itu_observation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $itu_is_visible;

    /**
     * @ORM\ManyToOne(targetEntity=CtUtilisation::class, inversedBy="ctImprimeTechUses")
     */
    private $ct_utilisation_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCtBordereauId(): ?CtBordereau
    {
        return $this->ct_bordereau_id;
    }

    public function setCtBordereauId(?CtBordereau $ct_bordereau_id): self
    {
        $this->ct_bordereau_id = $ct_bordereau_id;

        return $this;
    }

    public function getCtCentreId(): ?CtCentre
    {
        return $this->ct_centre_id;
    }

    public function setCtCentreId(?CtCentre $ct_centre_id): self
    {
        $this->ct_centre_id = $ct_centre_id;

        return $this;
    }

    public function getCtImprimeTechId(): ?CtImprimeTech
    {
        return $this->ct_imprime_tech_id;
    }

    public function setCtImprimeTechId(?CtImprimeTech $ct_imprime_tech_id): self
    {
        $this->ct_imprime_tech_id = $ct_imprime_tech_id;

        return $this;
    }

    public function getCtUserId(): ?CtUser
    {
        return $this->ct_user_id;
    }

    public function setCtUserId(?CtUser $ct_user_id): self
    {
        $this->ct_user_id = $ct_user_id;

        return $this;
    }

    public function getCtControleId(): ?int
    {
        return $this->ct_controle_id;
    }

    public function setCtControleId(?int $ct_controle_id): self
    {
        $this->ct_controle_id = $ct_controle_id;

        return $this;
    }

    public function getItuNumero(): ?int
    {
        return $this->itu_numero;
    }

    public function setItuNumero(int $itu_numero): self
    {
        $this->itu_numero = $itu_numero;

        return $this;
    }

    public function isItuUsed(): ?bool
    {
        return $this->itu_used;
    }

    public function setItuUsed(bool $itu_used): self
    {
        $this->itu_used = $itu_used;

        return $this;
    }

    public function getCtUsageItId(): ?CtUsageImprimeTechnique
    {
        return $this->ct_usage_it_id;
    }

    public function setCtUsageItId(?CtUsageImprimeTechnique $ct_usage_it_id): self
    {
        $this->ct_usage_it_id = $ct_usage_it_id;

        return $this;
    }

    public function getActivedAt(): ?\DateTimeInterface
    {
        return $this->actived_at;
    }

    public function setActivedAt(?\DateTimeInterface $actived_at): self
    {
        $this->actived_at = $actived_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getItuObservation(): ?string
    {
        return $this->itu_observation;
    }

    public function setItuObservation(?string $itu_observation): self
    {
        $this->itu_observation = $itu_observation;

        return $this;
    }

    public function isItuIsVisible(): ?bool
    {
        return $this->itu_is_visible;
    }

    public function setItuIsVisible(bool $itu_is_visible): self
    {
        $this->itu_is_visible = $itu_is_visible;

        return $this;
    }

    public function getCtUtilisationId(): ?CtUtilisation
    {
        return $this->ct_utilisation_id;
    }

    public function setCtUtilisationId(?CtUtilisation $ct_utilisation_id): self
    {
        $this->ct_utilisation_id = $ct_utilisation_id;

        return $this;
    }

    /**
    * toString
    * @return string
    */
    public function __toString()
    {
        return $this->getCtImprimeTechId().' -> '.$this->getItuNumero();
    }
}

src/Form/CtImprimeTechUseType.php
<?php

namespace App\Form;

use App\Entity\CtImprimeTechUse;
use DateTime;
use Symfony\Component\Form\AbstractType;
use App\Entity\CtImprimeTech;
use App\Repository\CtImprimeTechRepository;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class CtImprimeTechUseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $visible = [
            'Oui' => true,
            'Non' => false
        ];
        $utiliser = [
            'Oui' => true,
            'Non' => false
        ];
        $builder
            ->add('ct_controle_id', null, [
                'label' => 'Controle id',
            ])
            ->add('itu_numero', null, [
                'label' => 'Numéro d\'imprimé technique',
            ])
            ->add('itu_used', ChoiceType::class, [
                'label' => 'Imprimé technique utilisé',
                'choices' => $utiliser,
                'data' => false,
            ])
            ->add('actived_at', DateTimeType::class, [
                'label' => 'Date d\'activation',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datetimepicker',
                ],
                'data' => new \DateTime('now'),
            ])
            ->add('created_at', DateTimeType::class, [
                'label' => 'Date de création',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datetimepicker',
                ],
                'data' => new \DateTime('now'),
            ])
            ->add('updated_at', DateTimeType::class, [
                'label' => 'Date de modification',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datetimepicker',
                ],
                'data' => new \DateTime('now'),
            ])
            ->add('itu_observation', null, [
                'label' => 'Observation',
            ])
            ->add('itu_is_visible', ChoiceType::class, [
                'label' => 'Est-visible',
                'choices' => $visible,
                'data' => false,
            ])
            ->add('ct_bordereau_id', null, [
                'label' => 'Bordereau',
            ])
            ->add('ct_centre_id', null, [
                'label' => 'Centre',
            ])
            ->add('ct_imprime_tech_id', null, [
                'label' => 'Imprimé technique',
            ])
            ->add('ct_user_id', null, [
                'label' => 'Utilisateur',
            ])
            ->add('ct_usage_it_id', null, [
                'label' => 'Utilisation',
            ])
            ->add('ct_utilisation_id', null, [
                'label' => 'Utilisation',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CtImprimeTechUse::class,
        ]);
    }
}

src/Controller/CtImprimeTechUseController.php
<?php

namespace App\Controller;

use App\Entity\CtImprimeTechUse;
use App\Form\CtImprimeTechUseType;
use App\Repository\CtImprimeTechUseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/ct_imprime_tech_use")
 */
class CtImprimeTechUseController extends AbstractController
{
    /**
     * @Route("/", name="app_ct_imprime_tech_use_index", methods={"GET"})
     */
    public function index(CtImprimeTechUseRepository $ctImprimeTechUseRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $ctImprimeTechUseRepository->findBy([], ["id" => "DESC"]), /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            100/*limit per page*/
        );
        return $this->render('ct_imprime_tech_use/index.html.twig', [
            'ct_imprime_tech_uses' => $pagination,
        ]);
    }

    /**
     * @Route("/new", name="app_ct_imprime_tech_use_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CtImprimeTechUseRepository $ctImprimeTechUseRepository): Response
    {
        $ctImprimeTechUse = new CtImprimeTechUse();
        $form = $this->createForm(CtImprimeTechUseType::class, $ctImprimeTechUse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ctImprimeTechUseRepository->add($ctImprimeTechUse, true);

            return $this->redirectToRoute('app_ct_imprime_tech_use_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ct_imprime_tech_use/new.html.twig', [
            'ct_imprime_tech_use' => $ctImprimeTechUse,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ct_imprime_tech_use_show", methods={"GET"})
     */
    public function show(CtImprimeTechUse $ctImprimeTechUse): Response
    {
        return $this->render('ct_imprime_tech_use/show.html.twig', [
            'ct_imprime_tech_use' => $ctImprimeTechUse,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_ct_imprime_tech_use_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, CtImprimeTechUse $ctImprimeTechUse, CtImprimeTechUseRepository $ctImprimeTechUseRepository): Response
    {
        $form = $this->createForm(CtImprimeTechUseType::class, $ctImprimeTechUse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ctImprimeTechUseRepository->add($ctImprimeTechUse, true);

            return $this->redirectToRoute('app_ct_imprime_tech_use_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ct_imprime_tech_use/edit.html.twig', [
            'ct_imprime_tech_use' => $ctImprimeTechUse,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ct_imprime_tech_use_delete", methods={"POST"})
     */
    public function delete(Request $request, CtImprimeTechUse $ctImprimeTechUse, CtImprimeTechUseRepository $ctImprimeTechUseRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ctImprimeTechUse->getId(), $request->request->get('_token'))) {
            $ctImprimeTechUseRepository->remove($ctImprimeTechUse, true);
        }

        return $this->redirectToRoute('app_ct_imprime_tech_use_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ct_imprime_tech_use/_delete_form.html.twig
<form method="post" action="{{ path('app_ct_imprime_tech_use_delete', {'id': ct_imprime_tech_use.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ct_imprime_tech_use.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</button>
</form>

templates/ct_imprime_tech_use/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <table class="table" style="width:450px;">
        <tbody>
            <tr>
                <td style="width:150px;">
    <button class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> {{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/ct_imprime_tech_use/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition Imprimé Technique Utilisé{% endblock %}

{% block body %}
    <div class="box-header">Edition Imprimé Technique Utilisé</div><br>

    {{ include('ct_imprime_tech_use/_form.html.twig', {'button_label': 'Modifier'}) }}
            </td>
            <td style="width:150px;">
    <a href="{{ path('app_ct_imprime_tech_use_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
            </td>
            <td style="width:150px;">
    {{ include('ct_imprime_tech_use/_delete_form.html.twig') }}
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ct_imprime_tech_use/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Imprimé Technique Utilisé{% endblock %}

{% block body %}
    <div class="box-header">Liste Imprimé Technique Utilisé</div><br>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>controle_id</th>
                <th>numéro</th>
                <th>utilisé</th>
                <th>Actived_at</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>observation</th>
                <th>est visible</th>
                <th>Utilisation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ct_imprime_tech_use in ct_imprime_tech_uses %}
            <tr>
                <td>{{ ct_imprime_tech_use.id }}</td>
                <td>{{ ct_imprime_tech_use.ctControleId }}</td>
                <td>{{ ct_imprime_tech_use.ituNumero }}</td>
                <td>{{ ct_imprime_tech_use.ituUsed ? 'Oui' : 'Non' }}</td>
                <td>{{ ct_imprime_tech_use.activedAt ? ct_imprime_tech_use.activedAt|date('d/m/Y H:i:s') : '' }}</td>
                <td>{{ ct_imprime_tech_use.createdAt ? ct_imprime_tech_use.createdAt|date('d/m/Y H:i:s') : '' }}</td>
                <td>{{ ct_imprime_tech_use.updatedAt ? ct_imprime_tech_use.updatedAt|date('d/m/Y H:i:s') : '' }}</td>
                <td>{{ ct_imprime_tech_use.ituObservation }}</td>
                <td>{{ ct_imprime_tech_use.ituIsVisible ? 'Oui' : 'Non' }}</td>
                <td>{{ ct_imprime_tech_use.ctUtilisationId }}</td>
                <td>
                    <a href="{{ path('app_ct_imprime_tech_use_show', {'id': ct_imprime_tech_use.id}) }}" class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i></a>
                    <a href="{{ path('app_ct_imprime_tech_use_edit', {'id': ct_imprime_tech_use.id}) }}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="navigation">
        {{ knp_pagination_render(ct_imprime_tech_uses) }}
    </div>

    <a href="{{ path('app_ct_imprime_tech_use_new') }}" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Ajouter</a>
{% endblock %}

templates/ct_imprime_tech_use/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout Imprimé Technique Utilisé{% endblock %}

{% block body %}
    <div class="box-header">Ajout Imprimé Technique Utilisé</div><br>

    {{ include('ct_imprime_tech_use/_form.html.twig') }}
            </td>
            <td style="width:150px;">
    <a href="{{ path('app_ct_imprime_tech_use_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ct_imprime_tech_use/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Imprimé Technique Utilisé{% endblock %}

{% block body %}
    <div class="box-header">Imprimé Technique Utilisé</div><br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ct_imprime_tech_use.id }}</td>
            </tr>
            <tr>
                <th>controle_id</th>
                <td>{{ ct_imprime_tech_use.ctControleId }}</td>
            </tr>
            <tr>
                <th>numéro</th>
                <td>{{ ct_imprime_tech_use.ituNumero }}</td>
            </tr>
            <tr>
                <th>Utilisé</th>
                <td>{{ ct_imprime_tech_use.ituUsed ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>Actived_at</th>
                <td>{{ ct_imprime_tech_use.activedAt ? ct_imprime_tech_use.activedAt|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ ct_imprime_tech_use.createdAt ? ct_imprime_tech_use.createdAt|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ ct_imprime_tech_use.updatedAt ? ct_imprime_tech_use.updatedAt|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>observation</th>
                <td>{{ ct_imprime_tech_use.ituObservation }}</td>
            </tr>
            <tr>
                <th>est-visible</th>
                <td>{{ ct_imprime_tech_use.ituIsVisible ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>utilisation</th>
                <td>{{ ct_imprime_tech_use.ctUtilisationId }}</td>
            </tr>
        </tbody>
    </table>
	
	<table class="table" style="width:450px;">
        <tbody>
            <tr>
                <td style="width:150px;">
                    <a href="{{ path('app_ct_imprime_tech_use_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
                </td>
                <td style="width:150px;">
                    <a href="{{ path('app_ct_imprime_tech_use_edit', {'id': ct_imprime_tech_use.id}) }}" class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> Modifier</a>
                </td>
                <td style="width:150px;">
                    {{ include('ct_imprime_tech_use/_delete_form.html.twig') }} 
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}