src/Entity/CtGenreTarif.php
<?php

namespace App\Entity;

use App\Repository\CtGenreTarifRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CtGenreTarifRepository::class)
 */
class CtGenreTarif
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=CtGenre::class, inversedBy="ctGenreTarifs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ct_genre_id;

    /**
     * @ORM\Column(type="float")
     */
    private $grt_prix;

    /**
     * @ORM\Column(type="date")
     */
    private $grt_annee;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCtGenreId(): ?CtGenre
    {
        return $this->ct_genre_id;
    }

    public function setCtGenreId(?CtGenre $ct_genre_id): self
    {
        $this->ct_genre_id = $ct_genre_id;

        return $this;
    }

    public function getGrtPrix(): ?float
    {
        return $this->grt_prix;
    }

    public function setGrtPrix(float $grt_prix): self
    {
        $this->grt_prix = $grt_prix;

        return $this;
    }

    public function getGrtAnnee(): ?\DateTimeInterface
    {
        return $this->grt_annee;
    }

    public function setGrtAnnee(\DateTimeInterface $grt_annee): self
    {
        $this->grt_annee = $grt_annee;

        return $this;
    }

    /**
    * toString
    * @return string
    */
    public function __toString()
    {
        return $this->getGrtPrix();
    }
}

src/Form/CtGenreTarifType.php
<?php

namespace App\Form;

use App\Entity\CtGenreTarif;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CtGenreTarifType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('grt_prix', null, [
                'label' => 'Prix',
            ])
            ->add('grt_annee', null, [
                'label' => 'Année',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datetimepicker',
                ],
                'data' => new \DateTime('now'),
            ])
            ->add('ct_genre_id', null, [
                'label' => 'Genre',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CtGenreTarif::class,
        ]);
    }
}

src/Controller/CtGenreTarifController.php
<?php

namespace App\Controller;

use App\Entity\CtGenreTarif;
use App\Form\CtGenreTarifType;
use App\Repository\CtGenreTarifRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/ct_genre_tarif")
 */
class CtGenreTarifController extends AbstractController
{
    /**
     * @Route("/", name="app_ct_genre_tarif_index", methods={"GET"})
     */
    public function index(CtGenreTarifRepository $ctGenreTarifRepository): Response
    {
        return $this->render('ct_genre_tarif/index.html.twig', [
            'ct_genre_tarifs' => $ctGenreTarifRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_ct_genre_tarif_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CtGenreTarifRepository $ctGenreTarifRepository): Response
    {
        $ctGenreTarif = new CtGenreTarif();
        $form = $this->createForm(CtGenreTarifType::class, $ctGenreTarif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ctGenreTarifRepository->add($ctGenreTarif, true);

            return $this->redirectToRoute('app_ct_genre_tarif_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ct_genre_tarif/new.html.twig', [
            'ct_genre_tarif' => $ctGenreTarif,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ct_genre_tarif_show", methods={"GET"})
     */
    public function show(CtGenreTarif $ctGenreTarif): Response
    {
        return $this->render('ct_genre_tarif/show.html.twig', [
            'ct_genre_tarif' => $ctGenreTarif,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_ct_genre_tarif_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, CtGenreTarif $ctGenreTarif, CtGenreTarifRepository $ctGenreTarifRepository): Response
    {
        $form = $this->createForm(CtGenreTarifType::class, $ctGenreTarif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ctGenreTarifRepository->add($ctGenreTarif, true);

            return $this->redirectToRoute('app_ct_genre_tarif_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ct_genre_tarif/edit.html.twig', [
            'ct_genre_tarif' => $ctGenreTarif,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ct_genre_tarif_delete", methods={"POST"})
     */
    public function delete(Request $request, CtGenreTarif $ctGenreTarif, CtGenreTarifRepository $ctGenreTarifRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ctGenreTarif->getId(), $request->request->get('_token'))) {
            $ctGenreTarifRepository->remove($ctGenreTarif, true);
        }

        return $this->redirectToRoute('app_ct_genre_tarif_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ct_genre_tarif/_delete_form.html.twig
<form method="post" action="{{ path('app_ct_genre_tarif_delete', {'id': ct_genre_tarif.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ct_genre_tarif.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</button>
</form>

templates/ct_genre_tarif/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <table class="table" style="width:450px;">
        <tbody>
            <tr>
                <td style="width:150px;">
    <button class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> {{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/ct_genre_tarif/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition Tarif Genre{% endblock %}

{% block body %}
    <div class="box-header">Edition Tarif Genre</div><br>

    {{ include('ct_genre_tarif/_form.html.twig', {'button_label': 'Modifier'}) }}
            </td>
            <td style="width:150px;">
    <a href="{{ path('app_ct_genre_tarif_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
            </td>
            <td style="width:150px;">
    {{ include('ct_genre_tarif/_delete_form.html.twig') }}
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ct_genre_tarif/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Tarif Genre{% endblock %}

{% block body %}
    <div class="box-header">Liste Tarif Genre</div><br>

    <table class="table liste">
        <thead>
            <tr>
                <th>Id</th>
                <th>prix</th>
                <th>année</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ct_genre_tarif in ct_genre_tarifs %}
            <tr>
                <td>{{ ct_genre_tarif.id }}</td>
                <td>{{ ct_genre_tarif.grtPrix }}</td>
                <td>{{ ct_genre_tarif.grtAnnee ? ct_genre_tarif.grtAnnee|date('d/m/Y') : '' }}</td>
                <td>
                    <a href="{{ path('app_ct_genre_tarif_show', {'id': ct_genre_tarif.id}) }}" class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i></a>
                    <a href="{{ path('app_ct_genre_tarif_edit', {'id': ct_genre_tarif.id}) }}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <div class="navigation">
        {{ knp_pagination_render(ct_genre_tarifs) }}
    </div> #}

    <a href="{{ path('app_ct_genre_tarif_new') }}" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Ajouter</a>
{% endblock %}

templates/ct_genre_tarif/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout Tarif Genre{% endblock %}

{% block body %}
    <div class="box-header">Ajout Tarif Genre</div><br>

    {{ include('ct_genre_tarif/_form.html.twig') }}
            </td>
            <td style="width:150px;">
    <a href="{{ path('app_ct_genre_tarif_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ct_genre_tarif/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tarif Genre{% endblock %}

{% block body %}
    <div class="box-header">Tarif Genre</div><br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ct_genre_tarif.id }}</td>
            </tr>
            <tr>
                <th>prix</th>
                <td>{{ ct_genre_tarif.grtPrix }}</td>
            </tr>
            <tr>
                <th>année</th>
                <td>{{ ct_genre_tarif.grtAnnee ? ct_genre_tarif.grtAnnee|date('d/m/Y') : '' }}</td>
            </tr>
        </tbody>
    </table>
	
	<table class="table" style="width:450px;">
        <tbody>
            <tr>
                <td style="width:150px;">
                    <a href="{{ path('app_ct_genre_tarif_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
                </td>
                <td style="width:150px;">
                    <a href="{{ path('app_ct_genre_tarif_edit', {'id': ct_genre_tarif.id}) }}" class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> Modifier</a>
                </td>
                <td style="width:150px;">
                    {{ include('ct_genre_tarif/_delete_form.html.twig') }}
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}