src/Entity/CtGenreCategorie.php
<?php

namespace App\Entity;

use App\Repository\CtGenreCategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CtGenreCategorieRepository::class)
 */
class CtGenreCategorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gc_libelle;

    /**
     * @ORM\Column(type="boolean")
     */
    private $gc_is_calculable;

    /**
     * @ORM\OneToMany(targetEntity=CtGenre::class, mappedBy="ct_genre_categorie_id")
     */
    private $ctGenres;

    /**
     * @ORM\OneToMany(targetEntity=CtDroitPTAC::class, mappedBy="ct_genre_categorie_id")
     */
    private $ctDroitPTACs;

    public function __construct()
    {
        $this->ctGenres = new ArrayCollection();
        $this->ctDroitPTACs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGcLibelle(): ?string
    {
        return strtoupper($this->gc_libelle);
    }

    public function setGcLibelle(string $gc_libelle): self
    {
        $this->gc_libelle = strtoupper($gc_libelle);

        return $this;
    }

    public function isGcIsCalculable(): ?bool
    {
        return $this->gc_is_calculable;
    }

    public function setGcIsCalculable(bool $gc_is_calculable): self
    {
        $this->gc_is_calculable = $gc_is_calculable;

        return $this;
    }

    /**
     * @return Collection<int, CtGenre>
     */
    public function getCtGenres(): Collection
    {
        return $this->ctGenres;
    }

    public function addCtGenre(CtGenre $ctGenre): self
    {
        if (!$this->ctGenres->contains($ctGenre)) {
            $this->ctGenres[] = $ctGenre;
            $ctGenre->setCtGenreCategorieId($this);
        }

        return $this;
    }

    public function removeCtGenre(CtGenre $ctGenre): self
    {
        if ($this->ctGenres->removeElement($ctGenre)) {
            // set the owning side to null (unless already changed)
            if ($ctGenre->getCtGenreCategorieId() === $this) {
                $ctGenre->setCtGenreCategorieId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CtDroitPTAC>
     */
    public function getCtDroitPTACs(): Collection
    {
        return $this->ctDroitPTACs;
    }

    public function addCtDroitPTAC(CtDroitPTAC $ctDroitPTAC): self
    {
        if (!$this->ctDroitPTACs->contains($ctDroitPTAC)) {
            $this->ctDroitPTACs[] = $ctDroitPTAC;
            $ctDroitPTAC->setCtGenreCategorieId($this);
        }

        return $this;
    }

    public function removeCtDroitPTAC(CtDroitPTAC $ctDroitPTAC): self
    {
        if ($this->ctDroitPTACs->removeElement($ctDroitPTAC)) {
            // set the owning side to null (unless already changed)
            if ($ctDroitPTAC->getCtGenreCategorieId() === $this) {
                $ctDroitPTAC->setCtGenreCategorieId(null);
            }
        }

        return $this;
    }

    /**
    * toString
    * @return string
    */
    public function __toString()
    {
        return $this->getGcLibelle();
    }
}

src/Form/CtGenreCategorieType.php
<?php

namespace App\Form;

use App\Entity\CtGenreCategorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CtGenreCategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $calculable = [
            'Oui' => true,
            'Non' => false
        ];
        $builder
            ->add('gc_libelle', null, [
                'label' => 'Libellé',
            ])
            ->add('gc_is_calculable', ChoiceType::class, [
                'label' => 'Est-calculable',
                'choices' => $calculable,
                'data' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CtGenreCategorie::class,
        ]);
    }
}

src/Controller/CtGenreCategorieController.php
<?php

namespace App\Controller;

use App\Entity\CtGenreCategorie;
use App\Form\CtGenreCategorieType;
use App\Repository\CtGenreCategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/ct_genre_categorie")
 */
class CtGenreCategorieController extends AbstractController
{
    /**
     * @Route("/", name="app_ct_genre_categorie_index", methods={"GET"})
     */
    public function index(CtGenreCategorieRepository $ctGenreCategorieRepository): Response
    {
        return $this->render('ct_genre_categorie/index.html.twig', [
            'ct_genre_categories' => $ctGenreCategorieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_ct_genre_categorie_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CtGenreCategorieRepository $ctGenreCategorieRepository): Response
    {
        $ctGenreCategorie = new CtGenreCategorie();
        $form = $this->createForm(CtGenreCategorieType::class, $ctGenreCategorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ctGenreCategorieRepository->add($ctGenreCategorie, true);

            return $this->redirectToRoute('app_ct_genre_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ct_genre_categorie/new.html.twig', [
            'ct_genre_categorie' => $ctGenreCategorie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ct_genre_categorie_show", methods={"GET"})
     */
    public function show(CtGenreCategorie $ctGenreCategorie): Response
    {
        return $this->render('ct_genre_categorie/show.html.twig', [
            'ct_genre_categorie' => $ctGenreCategorie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_ct_genre_categorie_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, CtGenreCategorie $ctGenreCategorie, CtGenreCategorieRepository $ctGenreCategorieRepository): Response
    {
        $form = $this->createForm(CtGenreCategorieType::class, $ctGenreCategorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ctGenreCategorieRepository->add($ctGenreCategorie, true);

            return $this->redirectToRoute('app_ct_genre_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ct_genre_categorie/edit.html.twig', [
            'ct_genre_categorie' => $ctGenreCategorie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ct_genre_categorie_delete", methods={"POST"})
     */
    public function delete(Request $request, CtGenreCategorie $ctGenreCategorie, CtGenreCategorieRepository $ctGenreCategorieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ctGenreCategorie->getId(), $request->request->get('_token'))) {
            $ctGenreCategorieRepository->remove($ctGenreCategorie, true);
        }

        return $this->redirectToRoute('app_ct_genre_categorie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ct_genre_categorie/_delete_form.html.twig
<form method="post" action="{{ path('app_ct_genre_categorie_delete', {'id': ct_genre_categorie.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ct_genre_categorie.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</button>
</form>

templates/ct_genre_categorie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <table class="table" style="width:450px;">
        <tbody>
            <tr>
                <td style="width:150px;">
    <button class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> {{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/ct_genre_categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition Catégorie Genre{% endblock %}

{% block body %}
    <div class="box-header">Edition Catégorie Genre</div><br>

    {{ include('ct_genre_categorie/_form.html.twig', {'button_label': 'Modifier'}) }}
            </td>
            <td style="width:150px;">
    <a href="{{ path('app_ct_genre_categorie_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
            </td>
            <td style="width:150px;">
    {{ include('ct_genre_categorie/_delete_form.html.twig') }}
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ct_genre_categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Catégorie des Genres{% endblock %}

{% block body %}
    <div class="box-header">Liste Catégorie des Genres</div><br>

    <table class="table liste">
        <thead>
            <tr>
                <th>Id</th>
                <th>libellé</th>
                <th>est-calculable</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ct_genre_categorie in ct_genre_categories %}
            <tr>
                <td>{{ ct_genre_categorie.id }}</td>
                <td>{{ ct_genre_categorie.gcLibelle }}</td>
                <td>{{ ct_genre_categorie.gcIsCalculable ? 'Oui' : 'Non' }}</td>
                <td>
                    <a href="{{ path('app_ct_genre_categorie_show', {'id': ct_genre_categorie.id}) }}" class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i></a>
                    <a href="{{ path('app_ct_genre_categorie_edit', {'id': ct_genre_categorie.id}) }}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <div class="navigation">
        {{ knp_pagination_render(ct_genre_categories) }}
    </div> #}

    <a href="{{ path('app_ct_genre_categorie_new') }}" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Ajouter</a>
{% endblock %}

templates/ct_genre_categorie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout Catégorie du Genre{% endblock %}

{% block body %}
    <div class="box-header">Ajout Catégorie du Genre</div><br>

    {{ include('ct_genre_categorie/_form.html.twig') }}
            </td>
            <td style="width:150px;">
    <a href="{{ path('app_ct_genre_categorie_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/ct_genre_categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégorie du Genre{% endblock %}

{% block body %}
    <div class="box-header">Categorie du Genre</div><br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ct_genre_categorie.id }}</td>
            </tr>
            <tr>
                <th>libellé</th>
                <td>{{ ct_genre_categorie.gcLibelle }}</td>
            </tr>
            <tr>
                <th>est-calculable</th>
                <td>{{ ct_genre_categorie.gcIsCalculable ? 'Oui' : 'Non' }}</td>
            </tr>
        </tbody>
    </table>
	
	<table class="table" style="width:450px;">
        <tbody>
            <tr>
                <td style="width:150px;">
                    <a href="{{ path('app_ct_genre_categorie_index') }}" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Retour</a>
                </td>
                <td style="width:150px;">
                    <a href="{{ path('app_ct_genre_categorie_edit', {'id': ct_genre_categorie.id}) }}" class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> Modifier</a>
                </td>
                <td style="width:150px;">
                    {{ include('ct_genre_categorie/_delete_form.html.twig') }}
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}