src/Entity/CtVisite.php
<?php

namespace App\Entity;

use App\Repository\CtVisiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CtVisiteRepository::class)
 */
class CtVisite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=CtCarteGrise::class, inversedBy="ctVisites")
     */
    private $ct_carte_grise_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtCentre::class, inversedBy="ctVisites")
     */
    private $ct_centre_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtTypeVisite::class, inversedBy="ctVisites")
     */
    private $ct_type_visite_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtUsage::class, inversedBy="ctVisites")
     */
    private $ct_usage_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtUser::class, inversedBy="ctVisites")
     */
    private $ct_user_id;

    /**
     * @ORM\ManyToOne(targetEntity=CtUser::class, inversedBy="ctVisites")
     */
    private $ct_verificateur_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vst_num_pv;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vst_num_feuille_caisse;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $vst_date_expiration;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $vst_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $vst_updated;

    /**
     * @ORM\ManyToOne(targetEntity=CtUtilisation::class, inversedBy="ctVisites")
     */
    private $ct_utilisation_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vst_is_apte;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vst_is_contre_visite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vst_duree_reparation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vst_is_active;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $vst_genere;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vst_observation;

    /**
     * @ORM\ManyToMany(targetEntity=CtAnomalie::class, inversedBy="ctVisites", cascade={"persist", "remove"})
     */
    private $vst_anomalie_id;

    /**
     * @ORM\ManyToMany(targetEntity=CtVisiteExtra::class, inversedBy="ctVisites", cascade={"persist", "remove"})
     */
    private $vst_extra;

    /**
     * @ORM\OneToMany(targetEntity=CtExtraVente::class, mappedBy="ct_visite_id")
     */
    private $ctExtraVentes;

    /**
     * @ORM\ManyToMany(targetEntity=CtImprimeTech::class, inversedBy="ctVisites", cascade={"persist", "remove"})
     */
    private $vst_imprime_tech_id;

    public function __construct()
    {
        $this->vst_anomalie_id = new ArrayCollection();
        $this->vst_extra = new ArrayCollection();
        $this->ctExtraVentes = new ArrayCollection();
        $this->vst_imprime_tech_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCtCarteGriseId(): ?CtCarteGrise
    {
        return $this->ct_carte_grise_id;
    }

    public function setCtCarteGriseId(?CtCarteGrise $ct_carte_grise_id): self
    {
        $this->ct_carte_grise_id = $ct_carte_grise_id;

        return $this;
    }

    public function getCtCentreId(): ?CtCentre
    {
        return $this->ct_centre_id;
    }

    public function setCtCentreId(?CtCentre $ct_centre_id): self
    {
        $this->ct_centre_id = $ct_centre_id;

        return $this;
    }

    public function getCtTypeVisiteId(): ?CtTypeVisite
    {
        return $this->ct_type_visite_id;
    }

    public function setCtTypeVisiteId(?CtTypeVisite $ct_type_visite_id): self
    {
        $this->ct_type_visite_id = $ct_type_visite_id;

        return $this;
    }

    public function getCtUsageId(): ?CtUsage
    {
        return $this->ct_usage_id;
    }

    public function setCtUsageId(?CtUsage $ct_usage_id): self
    {
        $this->ct_usage_id = $ct_usage_id;

        return $this;
    }

    public function getCtUserId(): ?CtUser
    {
        return $this->ct_user_id;
    }

    public function setCtUserId(?CtUser $ct_user_id): self
    {
        $this->ct_user_id = $ct_user_id;

        return $this;
    }

    public function getCtVerificateurId(): ?CtUser
    {
        return $this->ct_verificateur_id;
    }

    public function setCtVerificateurId(?CtUser $ct_verificateur_id): self
    {
        $this->ct_verificateur_id = $ct_verificateur_id;

        return $this;
    }

    public function getVstNumPv(): ?string
    {
        return strtoupper($this->vst_num_pv);
    }

    public function setVstNumPv(?string $vst_num_pv): self
    {
        $this->vst_num_pv = strtoupper($vst_num_pv);

        return $this;
    }

    public function getVstNumFeuilleCaisse(): ?string
    {
        return strtoupper($this->vst_num_feuille_caisse);
    }

    public function setVstNumFeuilleCaisse(?string $vst_num_feuille_caisse): self
    {
        $this->vst_num_feuille_caisse = strtoupper($vst_num_feuille_caisse);

        return $this;
    }

    public function getVstDateExpiration(): ?\DateTimeInterface
    {
        return $this->vst_date_expiration;
    }

    public function setVstDateExpiration(?\DateTimeInterface $vst_date_expiration): self
    {
        $this->vst_date_expiration = $vst_date_expiration;

        return $this;
    }

    public function getVstCreated(): ?\DateTimeInterface
    {
        return $this->vst_created;
    }

    public function setVstCreated(?\DateTimeInterface $vst_created): self
    {
        $this->vst_created = $vst_created;

        return $this;
    }

    public function getVstUpdated(): ?\DateTimeInterface
    {
        return $this->vst_updated;
    }

    public function setVstUpdated(?\DateTimeInterface $vst_updated): self
    {
        $this->vst_updated = $vst_updated;

        return $this;
    }

    public function getCtUtilisationId(): ?CtUtilisation
    {
        return $this->ct_utilisation_id;
    }

    public function setCtUtilisationId(?CtUtilisation $ct_utilisation_id): self
    {
        $this->ct_utilisation_id = $ct_utilisation_id;

        return $this;
    }

    public function isVstIsApte(): ?bool
    {
        return $this->vst_is_apte;
    }

    public function setVstIsApte(bool $vst_is_apte): self
    {
        $this->vst_is_apte = $vst_is_apte;

        return $this;
    }

    public function isVstIsContreVisite(): ?bool
    {
        return $this->vst_is_contre_visite;
    }

    public function setVstIsContreVisite(bool $vst_is_contre_visite): self
    {
        $this->vst_is_contre_visite = $vst_is_contre_visite;

        return $this;
    }

    public function getVstDureeReparation(): ?string
    {
        return strtoupper($this->vst_duree_reparation);
    }

    public function setVstDureeReparation(?string $vst_duree_reparation): self
    {
        $this->vst_duree_reparation = strtoupper($vst_duree_reparation);

        return $this;
    }

    public function isVstIsActive(): ?bool
    {
        return $this->vst_is_active;
    }

    public function setVstIsActive(bool $vst_is_active): self
    {
        $this->vst_is_active = $vst_is_active;

        return $this;
    }

    public function getVstGenere(): ?int
    {
        return $this->vst_genere;
    }

    public function setVstGenere(?int $vst_genere): self
    {
        $this->vst_genere = $vst_genere;

        return $this;
    }

    public function getVstObservation(): ?string
    {
        return $this->vst_observation;
    }

    public function setVstObservation(?string $vst_observation): self
    {
        $this->vst_observation = $vst_observation;

        return $this;
    }

    /**
     * @return Collection<int, CtAnomalie>
     */
    public function getVstAnomalieId(): Collection
    {
        return $this->vst_anomalie_id;
    }

    public function addVstAnomalieId(CtAnomalie $vstAnomalieId): self
    {
        if (!$this->vst_anomalie_id->contains($vstAnomalieId)) {
            $this->vst_anomalie_id[] = $vstAnomalieId;
        }

        return $this;
    }

    public function removeVstAnomalieId(CtAnomalie $vstAnomalieId): self
    {
        $this->vst_anomalie_id->removeElement($vstAnomalieId);

        return $this;
    }

    /**
     * @return Collection<int, CtVisiteExtra>
     */
    public function getVstExtra(): Collection
    {
        return $this->vst_extra;
    }

    public function addVstExtra(CtVisiteExtra $vstExtra): self
    {
        if (!$this->vst_extra->contains($vstExtra)) {
            $this->vst_extra[] = $vstExtra;
        }

        return $this;
    }

    public function removeVstExtra(CtVisiteExtra $vstExtra): self
    {
        $this->vst_extra->removeElement($vstExtra);

        return $this;
    }

    /**
     * @return Collection<int, CtImprimeTech>
     */
    public function getVstImprimeTechId(): Collection
    {
        return $this->vst_imprime_tech_id;
    }

    public function addVstImprimeTechId(CtImprimeTech $vst_imprime_tech_id): self
    {
        if (!$this->vst_imprime_tech_id->contains($vst_imprime_tech_id)) {
            $this->vst_imprime_tech_id[] = $vst_imprime_tech_id;
        }

        return $this;
    }

    public function removeVstImprimeTechId(CtImprimeTech $vst_imprime_tech_id): self
    {
        $this->vst_imprime_tech_id->removeElement($vst_imprime_tech_id);

        return $this;
    }

    /**
     * @return Collection<int, CtExtraVente>
     */
    public function getCtExtraVentes(): Collection
    {
        return $this->ctExtraVentes;
    }

    public function addCtExtraVente(CtExtraVente $ctExtraVente): self
    {

templates/ct_app_visite/ajout_it_duplicata_authenticite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des imprimés utilisés{% endblock %}

{% block app_ct %}
<div class="box">
    <div class="box-header">UTILISATION IMPRIME</div><br>
</div>
<div class="box">
    <div class="entete-formulaire">Mise à jour utilisation des imprimés</div><hr>
    <div>
        {{ form_start(form_imprime_tech_use) }}
            {{ form_row(form_imprime_tech_use.ct_usage_it_id) }}
            {{ form_row(form_imprime_tech_use.ct_controle_id) }}
            {{ form_row(form_imprime_tech_use.ct_utilisation_id) }}
            {{ form_row(form_imprime_tech_use.imprime_technique_use_numero) }}
            <div align="left">
                <button class="btn btn-primary" type="submit" style="float:left">
                    Enregistrer
                </button>
            </div>
        {{ form_end(form_imprime_tech_use) }}
        <br><br>
    </div>
</div>
{% endblock %}

templates/ct_app_visite/ajout_it_mutation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des imprimés utilisés{% endblock %}

{% block app_ct %}
<div class="box">
    <div class="box-header">UTILISATION IMPRIME</div><br>
</div>
<div class="box">
    <div class="entete-formulaire">Mise à jour utilisation des imprimés</div><hr>
    <div>
        {{ form_start(form_imprime_tech_use) }}
            {{ form_row(form_imprime_tech_use.ct_usage_it_id) }}
            {{ form_row(form_imprime_tech_use.ct_controle_id) }}
            {{ form_row(form_imprime_tech_use.ct_utilisation_id) }}
            {{ form_row(form_imprime_tech_use.imprime_technique_use_numero) }}
            <div align="left">
                <button class="btn btn-primary" type="submit" style="float:left">
                    Enregistrer
                </button>
            </div>
        {{ form_end(form_imprime_tech_use) }}
        <br><br>
    </div>
</div>
{% endblock %}

templates/ct_app_visite/authenticite_vue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Authenticité{% endblock %}

{% block app_ct %}
    <div class="box-header">Authenticité</div><br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ct_autre_vente.id }}</td>
            </tr>
            <tr>
                <th>est-svisible</th>
                <td>{{ ct_autre_vente.auvIsVisible ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>created_at</th>
                <td>{{ ct_autre_vente.auvCreatedAt ? ct_autre_vente.auvCreatedAt|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Controle_id</th>
                <td>{{ ct_autre_vente.controleId }}</td>
            </tr>
        </tbody>
    </table>
	<a href="{{ path('app_ct_app_imprimable_authenticite', {'id': ct_autre_vente.id}) }}" class="btn btn-danger"><i class="fa fa-book" aria-hidden="true"></i> Imprimer</a>
{% endblock %}

templates/ct_app_visite/contre_visite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contre visite{% endblock %}

{% block app_ct %}
<div class="box">
    {# <div class="box-header-right"></div>
    <div class="box-header-left"></div> #}
    <div class="box-header">CONTRE VISITE</div>
</div>
<div class="box">
    <div class="entete-formulaire">Recherche</div><br>
    <div>
        <table class="table" style="width:100%;">
            <tbody>
                <tr>
                    <td style="width:50%;">
                        <form class="mt-2 mt-md-0 d-none d-lg-block search-input" action="{{ path('app_ct_app_visite_contre_visite') }}">
                            <div class="">
                                <strong>Par numéro d'immatriculation :</strong><br>
                                <span class="input-group-addon d-flex align-items-center"><i class="icon-magnifier icons"></i></span>
                                <input type="text" name="search-immatriculation" id="search-immatriculation" class="form-control" placeholder="numéro d'immatriculation...">
                                <button class="btn btn-primary" type="submit" style="float:right">
                                    Rechercher
                                </button>
                            </div>
                        </form>
                    </td>
                    <td style="width:50%;">
                        <form class="mt-2 mt-md-0 d-none d-lg-block search-input" action="{{ path('app_ct_app_visite_contre_visite') }}">
                            <div class="">
                                <strong>Par numéro dans la série du type :</strong><br>
                                <span class="input-group-addon d-flex align-items-center"><i class="icon-magnifier icons"></i></span>
                                <input type="text" name="search-numero-serie" id="search-numero-serie" class="form-control" placeholder="numéro de série...">
                                <button class="btn btn-primary" type="submit" style="float:right">
                                    Rechercher
                                </button>
                            </div>
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{# à mettre ici un message flash quand l'information véhicule n'existe pas #}
{% if recherche_ok == true and contre == false %}
    <div style="text-align:center;align:center;color:white;background-color:red">
        {{  message_indisponible_contre }}
    </div>
{% endif %}

{% if enregistrement_ok is not empty or enregistrement_ok is not null %}
    {% if enregistrement_ok == true %}
        <div style="text-align:center;align:center;color:white;background-color:green">
            {{ message }}
        </div>
    {% endif %}
    {% if enregistrement_ok == false %}
        <div style="text-align:center;align:center;color:white;background-color:red">
            {{ message }}
        </div>
    {% endif %}
{% endif %}

{{ form_start(form_visite) }}
    {# {{ form_widget(form_carte_grise.ct_vehicule_id) }} #}
    <table class="table bordure" style="width:100%;">
        <tbody>
            <tr>
                <td style="width:50%;">
                    <div class="box">
                        <div class="entete-formulaire">Information carte grise</div><hr>
                            {{ form_row(form_visite.ct_carte_grise_id.ct_centre_id) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_date_emission) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_immatriculation) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_num_identification) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_nom) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_prenom) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_profession) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_adresse) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_phone) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_commune) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_utilisation_id) }}
                            <hr>
                            {{ form_row(form_visite.ct_carte_grise_id.cg_is_transport) }}
                            <div class="sitransport">
                            {{ form_row(form_visite.ct_carte_grise_id.cg_nom_cooperative) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_itineraire) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_num_vignette) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_lieu_vignette) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_date_vignette) }}
                            {# {{ form_row(form_visite.ct_carte_grise_id.ct_zone_desserte_id) }} #}
                            </div>
                            <hr>
                            {{ form_row(form_visite.ct_carte_grise_id.cg_num_carte_violette) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_lieu_carte_violette) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_date_carte_violette) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_patente) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_ani) }}
                    </div>
                    <div class="box">
                        <div class="entete-formulaire">Information véhicule</div><hr>
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.ct_genre_id) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_type) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.ct_marque_id) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_num_serie) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_carrosserie_id) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_num_moteur) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_source_energie_id) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_cylindre) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_puissance) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_nbr_assis) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_poids_vide) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_charge_utile) }}
                            {{ form_row(form_visite.ct_carte_grise_id.ct_vehicule_id.vhc_poids_total_charge) }}
                            {{ form_row(form_visite.ct_carte_grise_id.cg_mise_en_service) }}
                    </div>
                </td>

                <td style="width:50%;">
                    <div class="box">
                        <div class="entete-formulaire">Information visite technique</div><hr>
                            {% if contre == false %}
                                <div style="visibility:hidden;">
                            {% else %}
                                <div>
                            {% endif %}
                                {{ form_row(form_visite.ct_centre_id) }}
                                {{ form_row(form_visite.ct_type_visite_id) }}
                                {{ form_row(form_visite.ct_usage_id) }}
                                {# {{ form_row(form_visite.ct_utilisation_id) }} #}
                                {{ form_row(form_visite.vst_anomalie_id) }}
                                <div class="duree">
                                {{ form_row(form_visite.vst_duree_reparation, { 'attr':{'disabled':'disabled'} }) }}
                                </div>
                                {{ form_row(form_visite.vst_date_expiration) }}
                                {{ form_row(form_visite.ct_verificateur_id) }}
                                {# {{ form_row(form_visite.vst_extra) }} #}
                                {% do form_visite.vst_extra.setRendered() %}
                            </div>
                    </div>
                </td>
            </tr>
            <tr>
            </tr>
        </tbody>
    </table>
    <div class="box">
        <button class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> {{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form_visite) }}
{% endblock %}

templates/ct_app_visite/creer_authenticite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attestation authenticité{% endblock %}

{% block app_ct %}
<div class="box">
    {# <div class="box-header-right"></div>
    <div class="box-header-left"></div> #}
    <div class="box-header">NOUVEAU ATTESTATION AUTHENTICITE</div>
</div>

{{ form_start(form_autre_vente) }}
    <div class="box">
        {{ form_widget(form_autre_vente) }}
    </div>
    <div class="box">
        <button class="btn btn-success"><i class="fa fa-book" aria-hidden="true"></i> {{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form_autre_vente) }}

{# à mettre ici un message flash quand l'information véhicule n'existe pas #}
{# {% if recherche_ok == true and contre == false %}
    <div style="text-align:center;align:center;color:white;background-color:red">
        {{  message_indisponible_contre }}
    </div>
{% endif %}

{% if enregistrement_ok is not empty or enregistrement_ok is not null %}
    {% if enregistrement_ok == true %}
        <div style="text-align:center;align:center;color:white;background-color:green">
            {{ message }}
        </div>
    {% endif %}
    {% if enregistrement_ok == false %}
        <div style="text-align:center;align:center;color:white;background-color:red">
            {{ message }}
        </div>
    {% endif %}
{% endif %} #}
{% endblock %}

templates/ct_app_visite/resume_modification.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulation visite{% endblock %}

{% block app_ct %}
<div class="box">
    <div class="box-header">RECAPITULATION DE MODIFICATION VISITE</div><br>
    <div>        
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ ct_visite.id }}</td>
                </tr>
                <tr>
                    <th>numéro pv</th>
                    <td>{{ ct_visite.vstNumPv }}</td>
                </tr>
                <tr>
                    <th>numéro feuille de caisse</th>
                    <td>{{ ct_visite.vstNumFeuilleCaisse }}</td>
                </tr>
                <tr>
                    <th>date expiration</th>
                    <td>{{ ct_visite.vstDateExpiration ? ct_visite.vstDateExpiration|date('d/m/Y') : '' }}</td>
                </tr>
                <tr>
                    <th>created</th>
                    <td>{{ ct_visite.vstCreated ? ct_visite.vstCreated|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>updated</th>
                    <td>{{ ct_visite.vstUpdated ? ct_visite.vstUpdated|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>est-apte</th>
                    <td>{{ ct_visite.vstIsApte ? 'Oui' : 'Non' }}</td>
                </tr>
                <tr>
                    <th>est-contre visite</th>
                    <td>{{ ct_visite.vstIsContreVisite ? 'Oui' : 'Non' }}</td>
                </tr>
                <tr>
                    <th>durée réparation</th>
                    <td>{{ ct_visite.vstDureeReparation }}</td>
                </tr>
                <tr>
                    <th>est-active</th>
                    <td>{{ ct_visite.vstIsActive ? 'Oui' : 'Non' }}</td>
                </tr>
                <tr>
                    <th>généré</th>
                    <td>{{ ct_visite.vstGenere }}</td>
                </tr>
                <tr>
                    <th>observation</th>
                    <td>{{ ct_visite.vstObservation }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{{ path('app_ct_app_imprimable_proces_verbal_visite_modification', {'id': ct_visite.id}) }}" class="btn btn-danger"><i class="fa fa-book" aria-hidden="true"></i> Imprimer</a>
    </div>
</div>
{% endblock %}

templates/ct_app_visite/resume_visite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulation visite{% endblock %}

{% block app_ct %}
<div class="box">
    <div class="box-header">RECAPITULATION DE CREATION VISITE</div><br>
    <div>        
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ ct_visite.id }}</td>
                </tr>
                <tr>
                    <th>numéro pv</th>
                    <td>{{ ct_visite.vstNumPv }}</td>
                </tr>
                <tr>
                    <th>numéro feuille de caisse</th>
                    <td>{{ ct_visite.vstNumFeuilleCaisse }}</td>
                </tr>
                <tr>
                    <th>date expiration</th>
                    <td>{{ ct_visite.vstDateExpiration ? ct_visite.vstDateExpiration|date('d/m/Y') : '' }}</td>
                </tr>
                <tr>
                    <th>created</th>
                    <td>{{ ct_visite.vstCreated ? ct_visite.vstCreated|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>updated</th>
                    <td>{{ ct_visite.vstUpdated ? ct_visite.vstUpdated|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>est-apte</th>
                    <td>{{ ct_visite.vstIsApte ? 'Oui' : 'Non' }}</td>
                </tr>
                <tr>
                    <th>est-contre visite</th>
                    <td>{{ ct_visite.vstIsContreVisite ? 'Oui' : 'Non' }}</td>
                </tr>
                <tr>
                    <th>durée réparation</th>
                    <td>{{ ct_visite.vstDureeReparation }}</td>
                </tr>
                <tr>
                    <th>est-active</th>
                    <td>{{ ct_visite.vstIsActive ? 'Oui' : 'Non' }}</td>
                </tr>
                <tr>
                    <th>généré</th>
                    <td>{{ ct_visite.vstGenere }}</td>
                </tr>
                <tr>
                    <th>observation</th>
                    <td>{{ ct_visite.vstObservation }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{{ path('app_ct_app_imprimable_proces_verbal_visite', {'id': ct_visite.id}) }}" class="btn btn-danger"><i class="fa fa-book" aria-hidden="true"></i> Imprimer</a>
    </div>
</div>
{% endblock %}